version: '3.7'
# How to use :
# > docker-compose build dev
# > docker-compose run -p 8888:8888 -p 5000:5000 -p 4321:4321  dev
## Then connect on provided URL to get jupyter lab


services:
  dev:
    image: hackatech_smartiot_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./data:/app/data
      - ./docker/notebooks:/app/notebooks
    ports :
      - 8888:8888
      - 4321:4321 #ports de sortie
      - 5000:5000 #ports en entree
    command: /app/start.sh
