version: '3.7'
# How to use :
# > docker-compose build dev
# > docker-compose run -p 8888:8888  dev


services:
  dev:
    image: hackatech_smartiot_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./docker:/app
    ports :
      - 8888:8888
    command: jupyter lab --allow-root --ip 0.0.0.0
