version: '3.7'
# How to use :
# > docker-compose build dev
# > docker-compose run -p 8888:8888  dev
## Then connect on provided URL to get jupyter lab


services:
  dev:
    image: hackatech_smartiot_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./docker/data:/app/data
      - ./docker/notebooks:/app/notebooks
    ports :
      - 8888:8888
    command: >
      /bin/bash -c "source /root/.bashrc && 
      jupyter server extension disable nbclassic &&  
      jupyter lab --allow-root --ip 0.0.0.0 "
