FROM continuumio/miniconda3

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

#Install packages
RUN apt-get update && apt-get install -y wget

WORKDIR /app
RUN conda update conda

#Create conda env 
RUN conda create --name nilmtk-env
RUN conda config --add channels conda-forge

# Make RUN commands use the new environment:
RUN echo "conda activate nilmtk-env" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

#Install nilmtk
RUN conda install -c nilmtk nilmtk

#Get dataset
RUN git clone https://github.com/ch-shin/ENERTALK-dataset.git /app/ENERTALK-dataset


#Install ENERTALK dependencies
COPY ./docker/requirements.* /app/
RUN pip install -r /app/requirements.dev.txt
RUN pip install -r /app/requirements.txt
