FROM python:3.9-slim-buster

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

#Install packages
RUN apt-get update && apt-get install -y libgomp1 curl wget

WORKDIR /app
ENV APP_WORKDIR /app

#Install python dependencies
COPY ./docker/requirements.* /app/
RUN pip install -r /app/requirements.dev.txt
RUN pip install -r /app/requirements.txt


RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version

RUN conda config --add channels conda-forge
RUN conda install -c nilmtk nilmtk
#RUN python -m pip install --upgrade --user ortools

